// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Uvse.Infrastructure.Persistence;

#nullable disable

namespace Uvse.Infrastructure.Migrations
{
    [DbContext(typeof(UvseDbContext))]
    [Migration("20260305230640_AddSummaryLlmProviderMetadata")]
    partial class AddSummaryLlmProviderMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Uvse.Domain.Datasources.Datasource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessScope")
                        .HasColumnType("integer");

                    b.Property<string>("ConnectionDetailsEncryptedJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("datasources", (string)null);
                });

            modelBuilder.Entity("Uvse.Domain.Datasources.DatasourceUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DatasourceId", "UserId")
                        .IsUnique();

                    b.ToTable("datasource_users", (string)null);
                });

            modelBuilder.Entity("Uvse.Domain.Plugins.TenantPlugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("EnabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedSettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProviderKey")
                        .IsUnique();

                    b.ToTable("tenant_plugins", (string)null);
                });

            modelBuilder.Entity("Uvse.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Uvse.Domain.Projects.ProjectDatasource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasourceId");

                    b.HasIndex("ProjectId", "DatasourceId")
                        .IsUnique();

                    b.ToTable("project_datasources", (string)null);
                });

            modelBuilder.Entity("Uvse.Domain.Projects.ProjectUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("project_users", (string)null);
                });

            modelBuilder.Entity("Uvse.Domain.Summaries.GeneratedSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AudienceTone")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ComparisonSummaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DatasourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("DetailLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LlmModel")
                        .HasColumnType("text");

                    b.Property<string>("LlmProviderKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestedModes")
                        .HasColumnType("integer");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "ProjectId", "DatasourceId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "RequestedByUserId", "TargetType", "ProjectId", "DatasourceId", "FromUtc", "ToUtc");

                    b.ToTable("generated_summaries", (string)null);
                });

            modelBuilder.Entity("Uvse.Domain.Datasources.DatasourceUser", b =>
                {
                    b.HasOne("Uvse.Domain.Datasources.Datasource", "Datasource")
                        .WithMany("DatasourceUsers")
                        .HasForeignKey("DatasourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datasource");
                });

            modelBuilder.Entity("Uvse.Domain.Projects.ProjectDatasource", b =>
                {
                    b.HasOne("Uvse.Domain.Datasources.Datasource", "Datasource")
                        .WithMany("ProjectDatasources")
                        .HasForeignKey("DatasourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uvse.Domain.Projects.Project", "Project")
                        .WithMany("ProjectDatasources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datasource");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Uvse.Domain.Projects.ProjectUser", b =>
                {
                    b.HasOne("Uvse.Domain.Projects.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Uvse.Domain.Datasources.Datasource", b =>
                {
                    b.Navigation("DatasourceUsers");

                    b.Navigation("ProjectDatasources");
                });

            modelBuilder.Entity("Uvse.Domain.Projects.Project", b =>
                {
                    b.Navigation("ProjectDatasources");

                    b.Navigation("ProjectUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
